# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [3]:
arr2 = np.array([1,1,1,1,1,1,1,1,1,1])

#### Create an array of 10 fives

In [4]:
arr3 = arr2*5

#### Create an array of the integers from 10 to 50

In [5]:
arr4 = np.array(range(10,51))

#### Create an array of all the even integers from 10 to 50

In [6]:
arr5 = np.array(range(10,51,2))

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
arr6 = np.array([[0,1,2],[3,4,5],[6,7,8]])

#### Create a 3x3 identity matrix

In [9]:
arr7 = np.array([[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]])

#### Use NumPy to generate a random number between 0 and 1

In [14]:
x = np.random.rand()
print(x)

0.8753627786138446


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [15]:
x = np.random.randn(25)
print(x)

[ 0.55721615 -1.55030596  0.4076431  -0.48984824  0.04650575 -1.17680672
  0.56452586 -0.61894874  1.42003043  0.96112961 -0.17741816  0.22311999
  1.25715563  0.9724038  -0.69241024 -0.19806322 -0.07680989 -0.31425024
  0.37879875 -1.4133356   1.28722969 -0.81549797 -1.28941829  0.44311164
 -1.2913319 ]


#### Create the following matrix:

In [16]:
arr10 = np.array(range(1,101))/100.0
print(arr10)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [18]:
x = np.array([x/19.0 for x in range(0,20)])
print(x)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [19]:
arr11 = np.array(range(1,26))
arr11 = arr11.reshape(5,5)
print(arr11)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [20]:
arr12 = arr11[2:,1:]
print(arr12)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [22]:
print(arr12[1,-1])

20


In [25]:
arr12 = arr11[0:3,1]
arr12 = arr12.reshape(3,-1)
print(arr12)

[[ 2]
 [ 7]
 [12]]


In [26]:
arr12 = arr11[-1]
arr12 = arr12.reshape(1,-1)
print(arr12)

[[21 22 23 24 25]]


In [27]:
arr12 = arr11[-2:]
print(arr12)

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!